GET http://localhost:3005/info
###
GET http://localhost:3005/api/persons/
###
GET http://localhost:3005/api/persons/1
###
GET http://localhost:3005/api/persons/999
###
POST http://localhost:3005/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "New Name",
  "number": "987-123456"
}
###
POST http://localhost:3005/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Arto Hellas",
  "number": "987-123400"
}
###
POST http://localhost:3005/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Same Number",
  "number": "12-43-234345"
}
###
POST http://localhost:3005/api/persons/ HTTP/1.1
content-type: application/json

{
  "number": "987-123456"
}
###
POST http://localhost:3005/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "No Number"

}
###
POST http://localhost:3005/api/persons/ HTTP/1.1
content-type: application/json

{

}
###
DELETE http://localhost:3005/api/persons/1